services:
  vuejs-app:
    build:
      context: ./dash
      dockerfile: Dockerfile
    networks:
      - app-network
    volumes:
      - nginx-config:/etc/nginx/conf.d

  django-api:
    build:
      context: ./api
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 myproject.wsgi:application
    volumes:
      - ./api:/app
      - nginx-config:/etc/nginx/conf.d
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - vuejs-app
      - django-api
    networks:
      - app-network
    volumes:
      - nginx-config:/etc/nginx/conf.d

networks:
  app-network:
    driver: bridge

volumes:
  nginx-config:
