# Generated by Django 5.0.4 on 2024-04-30 03:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_trainer_is_trainer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="is_superuser",
            field=models.BooleanField(default=False),
        ),
    ]
