# Generated by Django 5.0.6 on 2024-06-07 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_trainer_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='department_major',
            field=models.CharField(default='Major-default', max_length=255),
        ),
    ]
