# Use an official node runtime as a parent image
FROM node:20 as build-stage

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the app
RUN npm run build

# Production stage
FROM nginx:alpine as production-stage

# Copy the build output to the nginx html folder
COPY --from=build-stage /app/dist/spa /usr/share/nginx/html

# Copy custom nginx configuration if you have one
# COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port on which the app runs
EXPOSE 80

# Command to run the app
CMD ["nginx", "-g", "daemon off;"]
