# Use an official node runtime as a parent image
FROM node:14 as build-stage

# Set the working directory
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the app with limited resources
ENV NODE_OPTIONS="--max-old-space-size=512"
RUN npm run build

# Production stage
FROM nginx:alpine as production-stage

# Copy the build output to the nginx html folder
COPY --from=build-stage /app/dist/spa /usr/share/nginx/html

# Expose the port on which the app runs
EXPOSE 80

# Command to run the app
CMD ["nginx", "-g", "daemon off;"]
